version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ./app:/app/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ./app/db/queries/sql/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  front:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - 8001:8001
    depends_on:
      - app

    
volumes:
  postgres_data: